kind: pipeline
name: regular-deployer

steps:
- name: build-inventory
  image: apps.cavitos.net/rd-deployer:1.2
  environment:
    RD_API_URL:
      from_secret: RD_API_URL
  # volumes:
  # - name: cache
  #   path: /home/drone/cache
  commands: 
  - echo $DEPLOYMENT_ORDER_ID
  - pip3 install -r deployer/requirements.txt
  - python deployer/deployer.py --deployment-order-id=$DEPLOYMENT_ORDER_ID --api-url=$RD_API_URL --build-inventory
  - cat inventory.json
  - cat extra-vars.json

- name: deployment
  image: apps.cavitos.net/rd-deployer:1.2
  environment:
    RD_API_URL:
      from_secret: RD_API_URL
  # volumes:
  # - name: cache
  #   path: /home/drone/cache
  commands:
  - echo $DEPLOYMENT_ORDER_ID
  - pip3 install -r deployer/requirements.txt
  - python deployer/deployer.py --execute

image_pull_secrets:
- dockerconfigjson

# volumes:
# - name: cache
#   host:
#     path: /opt/cavitos/drone/drone

