kind: pipeline
name: regular-deployer

steps:
- name: build-inventory
  image: apps.cavitos.net/rd-deployer:1.0
  environment:
    RD_API_URL:
      from_secret: RD_API_URL
  commands: 
  - echo "Deployment Order: $DEPLOYMENT_ORDER_ID - API Url: $RD_API_URL"
  - pip3 install -r deployer/requirements.txt
  - python deployer/deployer.py --deployment-order-id=$DEPLOYMENT_ORDER_ID --api-url=$RD_API_URL --build-inventory

- name: deployment
  image: apps.cavitos.net/rd-deployer:1.0
  environment:
    RD_API_URL:
      from_secret: RD_API_URL
  commands:
  - echo "Deployment Order: $DEPLOYMENT_ORDER_ID - API Url: $RD_API_URL"
  - pip3 install -r deployer/requirements.txt
  - python deployer/deployer.py --execute

image_pull_secrets:
- dockerconfigjson
