kind: pipeline
name: regular-deployer

steps:
- name: python-version
  image: apps.cavitos.net/rd-deployer:1.0
  commands: 
  - python --version
  # when:
  #   branch:
  #   - master
  #   - feature/*

image_pull_secrets:
- dockerconfigjson